#!/usr/bin/env bash
# install_deps.sh
# Kamil Slowikowski
#
# Install dependencies for picardmetrics.

# Executables, libraries, and manpages will be put here with 'make install'.
if [[ "$1" == "" ]]; then
  PREFIX="$HOME/.local"
else
  PREFIX="$1"
fi

# Source code downloaded from the web will be put here.
SRC="$HOME/src"

main() {
  mkdir -p $PREFIX/bin
  mkdir -p $SRC

  cd $SRC

  # Picard
  VERSION=1.126
  if [[ ! -e "$SRC/picard-tools-${VERSION}/picard.jar" ]]; then
    URL="https://github.com/broadinstitute/picard/releases/download"
    if ! curl -k -L -O $URL/${VERSION}/picard-tools-${VERSION}.zip; then
      echo "Failed to download Picard"
      exit 1
    fi
    unzip picard-tools-${VERSION}.zip

    echo "Edit your picardmetrics.conf file to include:"
    echo "  PICARD_JAR=\"$SRC/picard-tools-${VERSION}/picard.jar\""
  fi

  # gtfToGenePred
  if [[ ! -e $PREFIX/bin/gtfToGenePred ]]; then
    url='http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/gtfToGenePred'
    wget $url -O $PREFIX/bin/gtfToGenePred && chmod +x $PREFIX/bin/gtfToGenePred
  fi

  # stats
  if [[ ! -e $PREFIX/bin/stats ]]; then
    git_clone arq5x/filo

    cd filo \
      && make \
      && cp bin/stats $PREFIX/bin/ \
      && cd ..
  fi

  # samtools
  if [[ ! -e $PREFIX/bin/samtools ]]; then
    git_clone samtools/htslib

    cd htslib \
      && make \
      && make prefix=$PREFIX install \
      && cd ..

    git_clone samtools/samtools

    cd samtools \
      && make \
      && make prefix=$PREFIX install \
      && cd ..
  fi

  if ! which gtfToGenePred || ! which stats || ! which samtools ; then
    echo
    echo "Add this to your .bashrc or .bash_profile:"
    echo "    PATH=\"\$HOME/.local/bin:\$PATH\""
  fi
}

git_clone() {
  USER_REPO=$1
  REPO=$(basename $USER_REPO)
  if [[ ! -d $REPO ]]; then
    if ! git clone https://github.com/${USER_REPO}; then
      echo "ERROR: Failed to download ${USER_REPO}"
      exit 1
    fi
  fi
}

main
