#!/usr/bin/env bash
# make_refFlat
# Kamil Slowikowski

set -o xtrace

# GENCODE
# 19 : Version 19 (July 2013 freeze, GRCh37, hg19) - Ensembl 74 or 75
# 22 : Version 22 (October 2014 freeze, GRCh38, hg38) - Ensembl 79
rel=19

DIR=data

GENCODE=$DIR/gencode.v${rel}.annotation.gtf.gz
REF_FLAT=$DIR/gencode.v${rel}.annotation.refFlat

# Download the Gencode GTF file.
GENCODE_URL="ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_human/release_${rel}/${GENCODE}"
[[ ! -s $GENCODE ]] && wget $GENCODE_URL -O $GENCODE

# Download a program for converting GTF to refFlat.
gtfToGenePred='http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/gtfToGenePred'
[[ ! -s scripts/gtfToGenePred ]] && \
	wget $gtfToGenePred -O scripts/gtfToGenePred \
	&& chmod +x scripts/gtfToGenePred

# Create the refFlat file suitable for use with Picard CollectRnaSeqMetrics.
if [[ ! -s $REF_FLAT ]]; then
	./scripts/gtfToGenePred \
		-ignoreGroupsWithoutExons <(gunzip -c $GENCODE) $REF_FLAT \
	&& perl -i -lane 'print join "\t", ($F[0], @F)' $REF_FLAT
	ERR=$?
	if [[ "$ERR" != 0 && "$ERR" != 255 ]]; then
		echo "Unexpected error $ERR from ./scripts/gtfToGenePred"
		exit 1
	fi
fi

