#!/usr/bin/env bash
# make_rRNA_intervals
# Kamil Slowikowski

set -o xtrace

# UCSC
# Feb. 2009 (hg19, GRCh37)
# Dec. 2013 (hg38, GRCh38)
hg=38

# GENCODE
# Version 19 (July 2013 freeze, GRCh37, hg19) - Ensembl 74
# Version 22 (October 2014 freeze, GRCh38, hg38) - Ensembl 79
rel=22

DIR=data

CHROM_SIZES=hg${rel}.chrom.sizes
GENCODE=gencode.v${rel}.annotation.gtf.gz
rRNA=gencode.v${rel}.rRNA.interval_list

# Download chromosome sizes from the UCSC genome browser.
if [[ ! -s $DIR/$CHROM_SIZES ]]
then
    mysql -N --user=genome --host=genome-mysql.cse.ucsc.edu -A -e \
        "SELECT chrom,size FROM chromInfo ORDER BY size DESC;" hg${hg} \
    > $DIR/$CHROM_SIZES
fi

# Download the Gencode GTF file.
GENCODE_URL="ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_human/release_${rel}/${GENCODE}"
if [[ ! -s $DIR/$GENCODE ]]; then
    wget $GENCODE_URL -O $DIR/$GENCODE
fi

# Create an interval list file suitable for Picard CollectRnaSeqMetrics.

if [[ ! -s $DIR/$rRNA ]]; then
    # Sequence names and lengths.
    perl -lane 'print "\@SQ\tSN:$F[0]\tLN:$F[1]\tAS:hg${hg}"' \
        $DIR/$CHROM_SIZES | \
    # Exclude chromosomes with "_" in their names.
        grep -v _ \
    > $DIR/$rRNA

    # Intervals for rRNA transcripts.
    grep 'gene_type "rRNA"' <(gunzip -c $DIR/$GENCODE) | \
        awk '$3 == "transcript"' | \
        cut -f1,4,5,7,9 | \
        perl -lane '
            /transcript_id "([^"]+)"/ or die "no transcript_id on $.";
            print join "\t", (@F[0,1,2,3], $1)
        ' | \
        sort -k1V -k2n -k3n \
    >> $DIR/$rRNA
fi
