#!/usr/bin/env bash
# make_rRNA_intervals
# Kamil Slowikowski

set -o xtrace

# UCSC
# 19 : Feb. 2009 (hg19, GRCh37)
# 38 : Dec. 2013 (hg38, GRCh38)
hg=19

# GENCODE
# 19 : Version 19 (July 2013 freeze, GRCh37, hg19) - Ensembl 74 or 75
# 22 : Version 22 (October 2014 freeze, GRCh38, hg38) - Ensembl 79
rel=19

DIR=data

GENCODE=$DIR/gencode.v${rel}.annotation.gtf.gz
rRNA=$DIR/gencode.v${rel}.rRNA.interval_list

# Download the Gencode GTF file.
GENCODE_URL="ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_human/release_${rel}/${GENCODE##*/}"
if [[ ! -s $GENCODE ]]; then
    wget $GENCODE_URL -O $GENCODE
fi

# Create an interval list file suitable for Picard CollectRnaSeqMetrics.
# Caveat: The header portion of this file will be generated on-the-fly by
# picardmetrics by taking the '@SQ' lines from the BAM file.
if [[ ! -s $rRNA ]]; then
    grep 'gene_type "rRNA"' <(gunzip -c $GENCODE) | \
        awk '$3 == "transcript"' | \
        cut -f1,4,5,7,9 | \
        perl -lane '
            /transcript_id "([^"]+)"/ or die "no transcript_id on $.";
            print join "\t", (@F[0,1,2,3], $1)
        ' | \
        sort -k1V -k2n -k3n \
    > $rRNA
fi
