#!/usr/bin/env bash
# make_rRNA_intervals
# Kamil Slowikowski

set -o xtrace

# Download chromosome sizes from the UCSC genome browser.
CHROM_SIZES=hg19.chrom.sizes
if [[ ! -s $CHROM_SIZES ]]
then
    mysql -N --user=genome --host=genome-mysql.cse.ucsc.edu -A -e \
        "SELECT chrom,size FROM chromInfo ORDER BY size DESC;" hg19 \
    > $CHROM_SIZES
fi

# Download the Gencode GTF file.
GENCODE=gencode.v19.annotation.gtf.gz
GENCODE_URL="ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_human/release_19/${GENCODE}"
[[ ! -s $GENCODE ]] && wget -q $GENCODE_URL

# Create an interval list file suitable for Picard CollectRnaSeqMetrics.
rRNA=gencode.v19.rRNA.interval_list

# Sequence names and lengths.
perl -lane 'print "\@SQ\tSN:$F[0]\tLN:$F[1]\tAS:hg19"' $CHROM_SIZES | \
# Exclude chromosomes with "_" in their names.
    grep -v _ \
> $rRNA

# Intervals for rRNA transcripts.
grep 'gene_type "rRNA"' <(gunzip -c $GENCODE) | \
    awk '$3 == "transcript"' | \
    cut -f1,4,5,7,9 | \
    perl -lane '
        /transcript_id "([^"]+)"/ or die "no transcript_id on $.";
        print join "\t", (@F[0,1,2,3], $1)
    ' | \
    sort -k1V -k2n -k3n \
>> $rRNA
